# Generated by Django 5.0.3 on 2024-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('age', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
