# Generated by Django 5.0.3 on 2024-03-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0006_alter_appointment_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='state',
            new_name='gender',
        ),
    ]
